/*
An enumeration for reducer actions
*/
export const actions = {
  CLOSEMENU: 'CLOSEMENU',
  GEO: 'GEO',
  SETINSPECTIONS: 'SETINSPECTIONS',
  REGEO: 'REGEO',
  COMMITS: 'COMMITS',
  SHOWGEO: 'SHOWGEO',
  NEARBY: 'NEARBY',
  NEAR: 'NEAR',
  PHO: 'PHO',
  SETVIEW: 'SETVIEW',
  INITSCREEN: 'INITSCREEN',
  SAVESCREEN: 'SAVESCREEN'
}
